4xx HttpStatus Codes Logged as Information
huseyinulas/GlobalExceptionFilter pull request #2
Opened 2018-10-20 09:23 UTC by yildirimabdullah

2018-10-20 13:46 UTC, AdemCatamak commented on GlobalExceptionFilter.App/HttpGlobalExceptionFilter.cs
> +            if (context.Exception.GetType() == typeof(CustomApiException))
if(context.Exception is CustomApiException customApiException)
{
}

Pattern matching is seems much more elegant

2018-10-23 11:56 UTC, huseyinulas-zz requested changes

2018-10-23 11:56 UTC, huseyinulas commented on GlobalExceptionFilter.App/HttpGlobalExceptionFilter.cs
> +                if (exception.ProblemDetails.Status < 500 && exception.ProblemDetails.Status >= 400)
Instead of 400 & 500, HttpStatus enumeration would be much better.

2018-10-26 12:33 UTC, huseyinulas-zz approved these changes

2018-10-26 12:33 UTC, merged

2018-10-28 08:14 UTC, AdemCatamak commented on GlobalExceptionFilter.App/HttpGlobalExceptionFilter.cs
> +                if (exception.ProblemDetails.Status < (int)HttpStatusCode.InternalServerError && exception.ProblemDetails.Status >= (int)HttpStatusCode.BadRequest)
line 56 should be removed. Morover, line 58 should converted to "customApiException.ProblemDetails..."